services:
  api:
    image: ${API_IMAGE:-petmanagerapi:latest}
    ports:
      - "${API_PORT:-8081}:8080"

  frontend:
    build: .
    ports:
      - "${FRONT_PORT:-8080}:80"
    depends_on:
      - api

